In [1]:
import pandas as pd
import glob
import os

# Path to the folder containing your CSV files
folder_path = "final_processed"  # Replace with the actual folder path
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# List to store DataFrames
dfs = []

# Loop through each file and add 'subject' column
for file in csv_files:
    # Read the CSV file without any headers
    df = pd.read_csv(file, header=None)
    
    # Add a 'subject' column with the file name (or any other unique identifier)
    df['subject'] = os.path.basename(file).split('.')[0]
    
    # Append to the list of DataFrames
    dfs.append(df)

# Concatenate all DataFrames without headers
combined_df = pd.concat(dfs, ignore_index=True)

# Assign column names after concatenation
# Assuming 1000 columns in original data, add 1 for 'subject'
combined_df.columns = [f"roi_{j}" for j in range(combined_df.shape[1] - 1)] + ['subject']

# Save to a single CSV file without an extra header
combined_df.to_csv("combined_file_with_subjects.csv", index=False)
print("All files have been combined into combined_file_with_subjects.csv")

All files have been combined into combined_file_with_subjects.csv

In [2]:
combined_df.head()

,roi_0,roi_1,roi_2,roi_3,roi_4,roi_5,roi_6,roi_7,roi_8,roi_9,...,roi_991,roi_992,roi_993,roi_994,roi_995,roi_996,roi_997,roi_998,roi_999,subject
0,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,...,991.000000,992.000000,993.000000,994.000000,995.000000,996.000000,997.000000,998.000000,999.000000,29880
1,2.998249,1.612865,3.292533,3.117657,5.390834,5.823775,4.102535,2.946094,3.774569,5.911536,...,4.619105,5.887983,4.831993,5.230559,5.331586,3.883421,5.257471,5.088832,3.964808,29880
2,0.461600,-0.765625,1.011972,0.571227,1.087854,1.157294,0.107912,1.553606,1.151092,1.349429,...,1.296141,2.850942,1.422155,1.505656,2.011614,1.100948,2.600782,2.748607,2.182474,29880
3,-0.705738,-0.652086,-0.932398,-0.390451,0.217905,0.541525,0.600391,0.363882,0.236667,-0.085301,...,-2.022708,0.165533,0.634620,0.191854,-0.257421,-0.427505,0.546791,0.512848,0.281318,29880
4,-0.116921,-0.625511,0.974322,0.360426,0.515688,0.791693,0.520980,1.272969,1.130235,1.382548,...,-0.360599,-0.065313,1.887860,1.476065,-0.333536,0.398168,1.753173,0.893996,0.130577,29880

In [3]:
combined_df.shape

(8372, 1001)

In [1]:
import pandas as pd
import glob

In [9]:
patients_metadata1 = pd.read_csv('/mnt/k/Abide Dataset/metadata/ABIDEII-EMC_1_CSV.csv')
meta2 = pd.read_csv('/mnt/k/Abide Dataset/metadata/ABIDEII-GU_1.csv', encoding = 'ISO-8859-1')

patients_metadata = pd.concat([patients_metadata1 , meta2])
patients_metadata.fillna(0)

,SITE_ID,SUB_ID,NDAR_GUID,DX_GROUP,PDD_DSM_IV_TR,ASD_DSM_5,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,...,ADI_R_C4_HIGHER,ADI_R_C4_UNUSUAL_SENSORY_INTERESTS,ADI_R_C4_TOTAL,ADI_R_D_AGE_PARENT_NOTICED,ADI_R_D_AGE_FIRST_SINGLE_WORDS,ADI_R_D_AGE_FIRST_PHRASES,ADI_R_D_AGE_WHEN_ABNORMALITY,ADI_R_D_INTERVIEWER_JUDGMENT,NON_ASD_PSY_DX_ICD9_CODE,NON_ASD_PSY_DX_LABEL
0,ABIDEII-EMC_1,29864,0.0,1,0.0,0.0,9.013005,1,2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ABIDEII-EMC_1,29865,0.0,1,0.0,0.0,10.663929,1,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABIDEII-EMC_1,29866,0.0,1,0.0,0.0,8.720055,1,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ABIDEII-EMC_1,29867,0.0,1,0.0,0.0,8.517454,2,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ABIDEII-EMC_1,29868,0.0,1,0.0,0.0,10.650240,1,2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,ABIDEII-GU_1,28841,0.0,2,0.0,0.0,8.723288,2,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,ABIDEII-GU_1,28842,0.0,2,0.0,0.0,8.408219,1,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,ABIDEII-GU_1,28845,0.0,2,0.0,0.0,8.390000,1,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,ABIDEII-GU_1,28846,0.0,2,0.0,0.0,8.740000,2,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105,ABIDEII-GU_1,28847,0.0,2,0.0,0.0,10.490000,1,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
print(patients_metadata.DX_GROUP.values)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2]